name: Build Succeed

on:
  pull_request:
    branches:
      - master

      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: set up node.js
        uses: actions/setup-node@v3
        with: 
         node-version: '20'
      
      - name: Install dependences
        run: npm install

      - name : prisma client
        run : npm run db:generate
        
        
      - name : run build
        run : npm run build  
       